### PR TITLE
fix: runtime call not found

### LINKED ISSUE #748: handle runtime call not found error
https://github.com/AcalaNetwork/chopsticks/blob/7703263adb6ac32d675c30ee3e3ea7bbe8f26cb0/executor/src/task.rs#L144

should propagate the error instead of unwrap

Screenshot 2024-05-02 at 9 27 55 PM

this will crash the program, but it should just return an error response.

### PR DESCRIPTION
**Pull request by qiweiii**
fix #748

### CODE REVIEW

File: executor/src/task.rs [hunk 1]
```diff
@@ -133,18 +133,23 @@ pub async fn run_task(task: TaskCall, js: crate::JsCallback) -> Result<TaskRespo
...
             function_to_call: call.as_str(),
             parameter: params.into_iter().map(|x| x.0),
             storage_main_trie_changes,
             max_log_level: task.runtime_log_level,
             calculate_trie_changes: false,
-        })
-        .unwrap();
+        });
 
         log::trace!("Calling {}", call);
```
Comment (xlc) [inline executor/src/task.rs:145]: move the log up before run. there isn't any reason it must be called after run and better to keep the result handling code together

File: executor/src/task.rs [hunk 2]
```diff
@@ -133,18 +133,23 @@ pub async fn run_task(task: TaskCall, js: crate::JsCallback) -> Result<TaskRespo
...
 
+        if let Err((start_err, _)) = vm_res {
+            return Ok(TaskResponse::Error(start_err.to_string()));
+        }
+
+        let mut vm = vm_res.unwrap();
```
Comment (xlc) [inline executor/src/task.rs:151]: should always avoid unwrap if possible

in this case, it can be written as
```rs
let vm = match vm {
  Ok(vm) => vm,
  Err((start_err, _)) => return Ok(TaskResponse::Error(start_err.to_string()));
}
```

Comment (xlc) [reply executor/src/task.rs:151]: and what is the `_` here? why we should ignore it? better to write it as `_xxx` so we know what it is and add a common if needed to explain why it can be ignored

**Review by xlc — APPROVED** [review]
